### ISSUE TITLE
Output format

### ISSUE THREAD

**Issue by erictuvesson** [translation/vue#1]
I am looking at the code right now before I look at integrating it to our workflow. And it seems that the output is in json, is that correct?

https://github.com/translation/vue/blob/master/src/commands/sync.js#L158-L167

It would be nice if there was a way to convert it to JS, for example:
```js
export default {
  welcome: 'Welcome'
}
```

**Comment by depsimon** [comment]
That's correct @erictuvesson 

Indeed that'd be a nice feature to be able to choose the output format. 

I'll add it to the roadmap.

**Comment by depsimon** [comment]
Hi @erictuvesson I just published a new release that allows you to read/write translations as JSON (by default) or Common Modules (`module.exports = {}`).

I haven't been able to add support for ES6 imports (`export default {}`).

I'll need more time to look into it.

**Comment by erictuvesson** [comment]
@depsimon You can close this issue; if you would like.

I am happy with the current results.

**Comment by depsimon** [comment]
Great, let me know if you see something else that could be improved :)
